---
- name: Sample IOS playbook to retrieve interface brief
  hosts: iosxe
  gather_facts: no

  tasks:
  - name: run show ip int brief
    cisco.ios.ios_command:
      commands: show ip interface brief
    register: myinterfaces

  - name: display value of "myinterfaces" variable
    debug:
      var: myinterfaces

  - name: display value of "myinterfaces["stdout_lines"][0]" variable
    debug:
      var: myinterfaces["stdout_lines"][0]